Create Nata288-NATALIA.json
I'm a programmer at my mother



You live calmly, watch your node, talk to her gently, collect revards every day and here !! the task set initially drove me to a dead end! ... No tutorials and no documentation !! Go there, I don’t know where, bring something, I don’t know what) But it was all the more interesting to solve this puzzle. At the time of this task, I had 1 Kchain node and 2 Rizon nodes, which were in the genesis. But no one knew what and how to do. Sleepless nights began in our Russian telegram group. Everyone was excited and the smartest, they began to think something out there, until it turned out !! What we cannot do is the task, since the nodes have not been updated. But we cannot be stopped. Alexey, armed with natural charisma from birth, solved this problem all night long, thereby infecting us all with his passion. For which I am deeply grateful to him. The first guide was his, which I tried on my node. Result minus 1 my Rizon node. But it's not about Alexey and his guide, it's about my knowledge, which was not enough for a complete result. Bloody rivers flowed across the monitor, from the red color of my node and errors. I had to kill her with my own hands. It's a pity of course, but what can you do. Sacrificed her for the sake of science and her own development. With emergency eyes full of blood, we sat at night trying to solve this puzzle. We became one close-knit team, thanks to this task. And a miracle happened. All the same, what smart people we have in Russia, what bright minds. This is not about myself, but about everyone else. I'm just a decent housewife, who during the quarantine was forced to master this knowledge, and I began to get at least something) And another guide was born, then another one and off we go. The result is minus 1 more node, killed to death in an unequal battle with the re-installer and plus a new node, fresh from the ground) Because the task must be completed. And some hashes, and some movements have already gone. And something started to work out, and then the test ended not in Reason. Blocks go to Rizon, but they don't want to go back. Or vice versa) But definitely in one direction. I'm not a programmer and I didn't even stand next to him. Although my mother told me ... learn English, and I German, learn computer science, and I geometry. But no one knew what would be useful in life) But this is not about that. If you have read all my nonsense to this point. I want to say huge words of gratitude to you for the fact that with your project and tasks, in our difficult time, you unite people who live in different parts of our planet. You give them the opportunity not only to learn something new and interesting, but to become a part of something big, previously unknown. And also the opportunity to help an absolutely stranger to complete this task, to prove themselves in the role of a mentor-teacher After all, just launching a node is, like a puzzle. If you do not fold it correctly, it will not work! And the more difficult the puzzle is, the more interesting it is to assemble it and the steeper the result at the end of the work. And after the end of all the testnets for Kitchain, he will forever remain in our memory with the best memories)
and a nervous tick of a twitching eye) And also thanks to our admins in the chat https://t.me/kichain_ru for the positive and good mood, help and emotional atmosphere.


Proof that I also became a part of the project) And I will tell my children and even grandchildren about it. Although I already have something to be proud of, I even know what a github is) I still don't know how to use it, but I know exactly what it is for.




hash(3D3FFBB9A830A70AF060141F834F6C6E98EBE48F0873C3FA93192CEAD2C8ACB0)

oot@ubuntu-8gb-fsn1-1:~# rly tx link transfer  --debug
I[2021-09-08|00:40:13.011] ★ Clients created: client(07-tendermint-45) on chain[groot-011] and client(07-tendermint-26) on chain[kichain-t-4]
I[2021-09-08|00:40:13.176] - attempting to create new connection ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:41:24.652] ✔ [groot-011]@{433682} - msg(0:update_client,1:connection_open_init) hash(3D3FFBB9A830A70AF060141F834F6C6E98EBE48F0873C3FA93192CEAD2C8ACB0)
I[2021-09-08|00:41:24.966] - chain[kichain-t-4] trying to open connection end on chain[groot-011]
rly paths list -d





I[2021-09-08|00:45:22.813] cannot submit an empty proof init: invalid proof [cosmos/cosmos-sdk@v0.42.4/x/ibc/core/03-connection/types/msgs.go:161]
I[2021-09-08|00:45:22.813] retrying transaction...
I[2021-09-08|00:45:28.935] - chain[kichain-t-4] trying to open connection end on chain[groot-011]
I[2021-09-08|00:45:35.659] ✔ [kichain-t-4]@{237157} - msg(0:update_client,1:connection_open_try) hash(C62C345A7454CD58501DE6AE0A942316FFEF4EAF0912C52EA442A3B6B298FD50)
I[2021-09-08|00:45:43.426] - [groot-011]@{{0 433718}}conn(connection-33)-{STATE_INIT} : [kichain-t-4]@{{4 237158}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:45:49.188] ✔ [groot-011]@{433719} - msg(0:update_client,1:connection_open_ack) hash(E4C70FF035654AF4A0D02A98B74E011FE9BFD1B73752C3511B8B45FF79EC72FD)
I[2021-09-08|00:45:53.334] - [groot-011]@{{0 433719}}conn(connection-33)-{STATE_INIT} : [kichain-t-4]@{{4 237159}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:45:53.664] rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: connection handshake open ack failed: connection state is not INIT or TRYOPEN (got STATE_OPEN): invalid connection state: invalid request
I[2021-09-08|00:45:53.664] retrying transaction...
I[2021-09-08|00:46:03.369] - [kichain-t-4]@{{4 237161}}conn(connection-123)-{STATE_TRYOPEN} : [groot-011]@{{0 433720}}conn(connection-33)-{STATE_OPEN}
I[2021-09-08|00:46:08.386] ✔ [kichain-t-4]@{237162} - msg(0:update_client,1:connection_open_confirm) hash(F271E9255D63A9936FBF353F4412B7C19443CB08F2F1D4C80C1013B47DA58837)
I[2021-09-08|00:46:08.420] - [groot-011]@{{0 433721}}conn(connection-33)-{STATE_OPEN} : [kichain-t-4]@{{4 237162}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:46:08.420] ★ Connection created: [groot-011]client{07-tendermint-45}conn{connection-33} -> [kichain-t-4]client{07-tendermint-26}conn{connection-123}
I[2021-09-08|00:46:08.779] - attempting to create new channel ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:46:08.966] rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: cannot update client with ID 07-tendermint-45: failed to verify header: invalid header: new header has a time from the future 2021-09-07 22:46:01.329312656 +0000 UTC (now: 2021-09-07 22:45:55.401600886 +0000 UTC; max clock drift: 5s): invalid request
I[2021-09-08|00:46:08.966] retrying transaction...
I[2021-09-08|00:46:18.761] - attempting to create new channel ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:46:24.908] ✔ [groot-011]@{433724} - msg(0:update_client,1:channel_open_init) hash(41C3B986C9F320F19AB5726F77E6D47D5B7F03B03B3E3CEFCFD68548403EC045)
I[2021-09-08|00:46:28.736] - chain[kichain-t-4] trying to open channel end on chain[groot-011]
I[2021-09-08|00:46:28.938] rpc error: code = InvalidArgument desc = cannot submit an empty proof init: invalid proof: invalid request


cdrly: command not found
root@ubuntu-8gb-fsn1-1:~# rly chains add -f groot-011.json
Error: invalid character '{' after top-level value
root@ubuntu-8gb-fsn1-1:~# rly light init groot-011 -f
successfully created light client for groot-011 by trusting endpoint http://localhost:26657...
root@ubuntu-8gb-fsn1-1:~# rly light init kichain-t-4 -f
successfully created light client for kichain-t-4 by trusting endpoint https://rpc-challenge.blockchain.ki:443...
root@ubuntu-8gb-fsn1-1:~# rly paths generate groot-011 kichain-t-4 transfer  -- port=transfer
Error: unknown flag: -- port
root@ubuntu-8gb-fsn1-1:~# rly paths generate groot-011 kichain-t-4 transfer  --port=transfer
Generated path(transfer ), run 'rly paths show transfer  --yaml' to see details
root@ubuntu-8gb-fsn1-1:~# rly tx link transfer  --debug
I[2021-09-08|00:40:13.011] ★ Clients created: client(07-tendermint-45) on chain[groot-011] and client(07-tendermint-26) on chain[kichain-t-4]
I[2021-09-08|00:40:13.176] - attempting to create new connection ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:41:24.652] ✔ [groot-011]@{433682} - msg(0:update_client,1:connection_open_init) hash(3D3FFBB9A830A70AF060141F834F6C6E98EBE48F0873C3FA93192CEAD2C8ACB0)
I[2021-09-08|00:41:24.966] - chain[kichain-t-4] trying to open connection end on chain[groot-011]
rly paths list -d
I[2021-09-08|00:45:22.813] cannot submit an empty proof init: invalid proof [cosmos/cosmos-sdk@v0.42.4/x/ibc/core/03-connection/types/msgs.go:161]
I[2021-09-08|00:45:22.813] retrying transaction...
I[2021-09-08|00:45:28.935] - chain[kichain-t-4] trying to open connection end on chain[groot-011]
I[2021-09-08|00:45:35.659] ✔ [kichain-t-4]@{237157} - msg(0:update_client,1:connection_open_try) hash(C62C345A7454CD58501DE6AE0A942316FFEF4EAF0912C52EA442A3B6B298FD50)
I[2021-09-08|00:45:43.426] - [groot-011]@{{0 433718}}conn(connection-33)-{STATE_INIT} : [kichain-t-4]@{{4 237158}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:45:49.188] ✔ [groot-011]@{433719} - msg(0:update_client,1:connection_open_ack) hash(E4C70FF035654AF4A0D02A98B74E011FE9BFD1B73752C3511B8B45FF79EC72FD)
I[2021-09-08|00:45:53.334] - [groot-011]@{{0 433719}}conn(connection-33)-{STATE_INIT} : [kichain-t-4]@{{4 237159}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:45:53.664] rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: connection handshake open ack failed: connection state is not INIT or TRYOPEN (got STATE_OPEN): invalid connection state: invalid request
I[2021-09-08|00:45:53.664] retrying transaction...
I[2021-09-08|00:46:03.369] - [kichain-t-4]@{{4 237161}}conn(connection-123)-{STATE_TRYOPEN} : [groot-011]@{{0 433720}}conn(connection-33)-{STATE_OPEN}
I[2021-09-08|00:46:08.386] ✔ [kichain-t-4]@{237162} - msg(0:update_client,1:connection_open_confirm) hash(F271E9255D63A9936FBF353F4412B7C19443CB08F2F1D4C80C1013B47DA58837)
I[2021-09-08|00:46:08.420] - [groot-011]@{{0 433721}}conn(connection-33)-{STATE_OPEN} : [kichain-t-4]@{{4 237162}}conn(connection-123)-{STATE_TRYOPEN}
I[2021-09-08|00:46:08.420] ★ Connection created: [groot-011]client{07-tendermint-45}conn{connection-33} -> [kichain-t-4]client{07-tendermint-26}conn{connection-123}
I[2021-09-08|00:46:08.779] - attempting to create new channel ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:46:08.966] rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: cannot update client with ID 07-tendermint-45: failed to verify header: invalid header: new header has a time from the future 2021-09-07 22:46:01.329312656 +0000 UTC (now: 2021-09-07 22:45:55.401600886 +0000 UTC; max clock drift: 5s): invalid request
I[2021-09-08|00:46:08.966] retrying transaction...
I[2021-09-08|00:46:18.761] - attempting to create new channel ends from chain[groot-011] with chain[kichain-t-4]
I[2021-09-08|00:46:24.908] ✔ [groot-011]@{433724} - msg(0:update_client,1:channel_open_init) hash(41C3B986C9F320F19AB5726F77E6D47D5B7F03B03B3E3CEFCFD68548403EC045)
I[2021-09-08|00:46:28.736] - chain[kichain-t-4] trying to open channel end on chain[groot-011]
I[2021-09-08|00:46:28.938] rpc error: code = InvalidArgument desc = cannot submit an empty proof init: invalid proof: invalid request
I[2021-09-08|00:46:28.938] retrying transaction...
I[2021-09-08|00:46:38.799] - chain[kichain-t-4] trying to open channel end on chain[groot-011]
I[2021-09-08|00:46:44.371] ✔ [kichain-t-4]@{237168} - msg(0:update_client,1:channel_open_try) hash(3369098A082554A5683B04505FED535CCCEA85CD19689143F4B0D53ACE0EDBB7)
I[2021-09-08|00:46:58.753] - [groot-011]@{{0 433728}}chan(channel-28)-{STATE_INIT} : [kichain-t-4]@{{4 237170}}chan(channel-120)-{STATE_TRYOPEN}
I[2021-09-08|00:47:06.245] ✔ [groot-011]@{433730} - msg(0:update_client,1:channel_open_ack) hash(3AB21AE5A49BA7F625DB60F3474637A197F982254BB3FA98725F145A64D67ADB)
I[2021-09-08|00:47:08.846] - [groot-011]@{{0 433730}}chan(channel-28)-{STATE_INIT} : [kichain-t-4]@{{4 237172}}chan(channel-120)-{STATE_TRYOPEN}
I[2021-09-08|00:47:09.344] rpc error: code = InvalidArgument desc = failed to execute message; message index: 1: channel handshake open ack failed: channel state should be INIT or TRYOPEN (got STATE_OPEN): invalid channel state: invalid request
I[2021-09-08|00:47:09.344] retrying transaction...
I[2021-09-08|00:47:18.788] - [kichain-t-4]@{{4 237173}}chan(channel-120)-{STATE_TRYOPEN} : [groot-011]@{{0 433731}}chan(channel-28)-{STATE_OPEN}
I[2021-09-08|00:47:26.535] ✔ [kichain-t-4]@{237175} - msg(0:update_client,1:channel_open_confirm) hash(E0027B91D962864BCDCD3238A20744531CF46F60BA4B38F262520B1648AAAC4F)
I[2021-09-08|00:47:26.574] - [groot-011]@{{0 433732}}chan(channel-28)-{STATE_OPEN} : [kichain-t-4]@{{4 237174}}chan(channel-120)-{STATE_TRYOPEN}
I[2021-09-08|00:47:26.574] ★ Channel created: [groot-011]chan{channel-28}port{transfer} -> [kichain-t-4]chan{channel-120}port{transfer}
root@ubuntu-8gb-fsn1-1:~# rly paths list -d
Error: chain with ID  is not configured
root@ubuntu-8gb-fsn1-1:~#